# Generated by Django 2.2.1 on 2019-05-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CADModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('checked_out', models.BooleanField(verbose_name=False)),
                ('ceation_date', models.DateTimeField(auto_now_add=True, verbose_name='date imported')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('coord_x', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='x coordinate')),
                ('coord_y', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='y coordinate')),
                ('coord_z', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='z coordinate')),
                ('comments', models.CharField(max_length=500)),
                ('cad_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadmodels.CADModel')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadmodels.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadmodels.Type')),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
    ]
