# Generated by Django 2.2.1 on 2019-05-03 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadmodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='marker_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cadmodel',
            name='ceation_date',
        ),
        migrations.AddField(
            model_name='cadmodel',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadmodel',
            name='checked_out',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
