# Generated by Django 2.2.1 on 2019-05-03 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadmodels', '0001_initial'),
        ('cadmodels', '0002_auto_20190503_1023')
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadmodel',
            name='ceation_date',
        ),
        migrations.AddField(
            model_name='cadmodel',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
